### ISSUE TITLE
PR in preparation

### ISSUE THREAD

**Issue by Mickaelh51** [OpenSIPS/sipssert-opensips-tests#1]
Hi,
I want to send my work about stir and shaken (only for authentication for now) => https://github.com/Mickaelh51/sipssert-opensips-tests/tree/stir_and_shaken_auth

1) But I use my own docker images for opensips and opensips-cli.
Because there is no stir and shaken module in opensips image and there is no python pyjwt module in opensips-cli image.

What is your preference ? Should I send a PR in your repos: docker-opensips-cli and docker-opensips ?

2) I added a private key in clear text in conf (generated by self-signed method), so github is not happy about that (Git guardian).

What are your best practices about this private key ? I would like to use this scenario very simply

thanks in advance

**Comment by razvancrainea** [comment]
Amazing @Mickaelh51 , thanks for your support!

Are your docker images publicly available in the Docker Hub? Because if they are, you can force your own images :).
If not, I can build the opensips image with the requested packages and push them in the `siprec` docker tag. Not sure what is the best way to do with the cli - perhaps your scripts/tests can pre-install it before running the tests?

Thanks!

**Comment by Mickaelh51** [comment]
Yes my images are available in docker hub (in public).
[opensips](https://hub.docker.com/r/allomediadocker/opensips)
[opensips-cli](https://hub.docker.com/r/allomediadocker/opensips-cli)

- But if I force my own images in `config.yml`, this file is sharing for all others scenarios. It works, but, I think you want to work with your officials images.

- For opensips-cli, in your dockerfile, you launch:
```
if [[ $CMD == *.py ]]; then
	TOOL=python3
elif [[ $CMD == *.sh ]]; then
	TOOL=bash
else
	TOOL=opensips-cli
fi

exec $TOOL $CMD $PARAMS
```

So, maybe I can call a subprocess to install pyJWT for each execution of container, But I think it's not clean and slowly to install dependencies on every container start.
I use PyJWT to parse Identity header and chek if keys are present.

maybe I can push my PR, and you could see exactly my questionnement. Is it ok for you ?

**Comment by Mickaelh51** [comment]
Hi,
I dedicated config.yml only for stir-shaken scenario (https://github.com/Mickaelh51/sipssert-opensips-tests/commit/6c2240b71388db231da4f0044865955619e679ec)
I will push my PR
