### ISSUE TITLE
How to format scenarios for future pull request

### ISSUE THREAD

**Issue by Mickaelh51** [OpenSIPS/sipssert-opensips-tests#4]
Hi,
I would like to create an PR for all my stir and shaken verify tests.
But 99% of my tests is usable for French providers.

Currently in stir and shaken directory we have:
- 01.auth-simple
- 02.auth-diverted-cached
- 03.auth-issue-bypass-token

what is the best way to format directories name of verify tests ? I have that in my local repo:

04.verify_ok_200
05.verify_error_400_5.5.2.3
06.verify_error_403_5.5.2.3
07.verify_error_403_5.5.2.4
08.verify_error_428_5.5.2.2
09.verify_error_436_5.5.2.3_no_info
10.verify_error_436_5.5.2.4_1
11.verify_error_436_5.5.2.4_2
12.verify_error_437_5.5.2.3_no_alg
13.verify_error_437_5.5.2.3_wrong_alg
14.verify_error_437_5.5.3.2_cert_expired
15.verify_error_437_5.5.3.2_cert_in_future

5.5.X.X it's sort of "IDs" that represent specifics tests into French regulation documentation. Is that OK for you if I add these "IDs" into directories name ? Or maybe add a prefix FR like this 05.FR_verify_error_400_5.5.2.3 ? Like you want.
Sure I will add description in repo's README, and diagrams + explanations into each directories

have a good day

**Comment by razvancrainea** [comment]
@Mickaelh51 my first impression is to keep things simple - therefore, I'd say to name them as they are, without a prefix or anything - at the end of the day, (French regulation) is a particular usage of the stir&shaken functionalities. If this becomes a problem in the future (i.e. somebody adds more generic stir&shaken tests), we can definitely rename the whole tests_set/directory to something like stir-shaken-fr, but I don't think that's needed right now.
I guess you can now consider it as being French related, and document the entire directory like so.

**Comment by Mickaelh51** [comment]
ok thanks for your answer.
have a good day

**Comment by Mickaelh51** [comment]
ha, last thing
FYI for this future PR, this one is mandatory https://github.com/OpenSIPS/SIPssert/pull/11 ;)

**Comment by razvancrainea** [comment]
It is now upstream, so feel free to publish the tests :). Thanks!
